[pantheon-torchyn]
type = sftp
host = appserver.dev.b14a704c-f33c-4557-ae95-71445cd68b6d.drush.in
user = dev.b14a704c-f33c-4557-ae95-71445cd68b6d
port = 2222
key_file = /Users/lindseycatlett/.ssh/id_rsa
shell_type = unix
md5sum_command = none
sha1sum_command = none

