# HK Ukraine remotes
[poc-hk]
type = sftp
host = appserver.dev.9c3b8d39-08df-4dac-a63a-7987118d857e.drush.in
user = dev.9c3b8d39-08df-4dac-a63a-7987118d857e
port = 2222
key_file = ~/.ssh/id_rsa
shell_type = unix
md5sum_command = none
sha1sum_command = none
concurrency = 8
connections = 4

[prod-hk]
type = sftp
host = appserver.dev.7423c32a-9e7d-4988-8bed-51ca891852ed.drush.in
user = dev.7423c32a-9e7d-4988-8bed-51ca891852ed
port = 2222
key_file = ~/.ssh/id_rsa
shell_type = unix
md5sum_command = none
sha1sum_command = none
concurrency = 8
connections = 4

# Torchyn remotes
[poc-torchyn]
type = sftp
host = appserver.dev.0bf84afd-e6c5-4324-bb64-126d9d5f816c.drush.in
user = dev.0bf84afd-e6c5-4324-bb64-126d9d5f816c
port = 2222
key_file = ~/.ssh/id_rsa
shell_type = unix
md5sum_command = none
sha1sum_command = none
concurrency = 8
connections = 4

[prod-torchyn]
type = sftp
host = appserver.dev.b14a704c-f33c-4557-ae95-71445cd68b6d.drush.in
user = dev.b14a704c-f33c-4557-ae95-71445cd68b6d
port = 2222
key_file = ~/.ssh/id_rsa
shell_type = unix
md5sum_command = none
sha1sum_command = none
concurrency = 8
connections = 4
