# Acquia remote
[acquia-risd-edu]
type = sftp
host = risdasf01live.ssh.enterprise-g1.acquia-sites.com
user = risdasf.01live
port = 22
key_file = ~/.ssh/id_rsa_migration
use_insecure_cipher = true
md5sum_command = md5sum
ask_password = true
shell_type = unix
sha1sum_command = sha1sum

# Pantheon remote
[pantheon-risd-main]
type = sftp
host = appserver.live.36ad8929-a961-4a57-90a7-2a4fdb93a55b.drush.in
user = live.36ad8929-a961-4a57-90a7-2a4fdb93a55b
port = 2222
key_file = ~/.ssh/id_rsa_migration
shell_type = unix
md5sum_command = none
sha1sum_command = none

# Pantheon remote
[pantheon-risd-registrar]
type = sftp
host = appserver.live.7d1788db-3c24-4e7a-b0d9-67517d9f7e71.drush.in
user = live.7d1788db-3c24-4e7a-b0d9-67517d9f7e71
port = 2222
key_file = ~/.ssh/id_rsa_migration
shell_type = unix
md5sum_command = none
sha1sum_command = none

[pantheon-risd-sfs]
type = sftp
host = appserver.live.709cf95a-ebc8-494f-b358-ff1ff766cbb0.drush.in
user = live.709cf95a-ebc8-494f-b358-ff1ff766cbb0
port = 2222
key_file = ~/.ssh/id_rsa_migration
shell_type = unix
md5sum_command = none
sha1sum_command = none

[pantheon-risd-students]
type = sftp
ost = appserver.live.14575238-3b6f-4249-b0ab-c16e9c2827e5.drush.in
user = live.14575238-3b6f-4249-b0ab-c16e9c2827e5
port = 2222
key_file = ~/.ssh/id_rsa_migration
shell_type = unix
md5sum_command = none
sha1sum_command = none

[pantheon-risd-teach]
type = sftp
host = appserver.live.bae2d332-b327-486d-b29c-834cc550c9df.drush.in
user = live.bae2d332-b327-486d-b29c-834cc550c9df
port = 2222
key_file = ~/.ssh/id_rsa_migration
shell_type = unix
md5sum_command = none
sha1sum_command = none

[ofx-com-live]
type = sftp
md5sum_command = none
sha1sum_command = none
host = appserver.live.ca056cd5-e2a6-4bd9-bef0-ab494f75c164.drush.in
user = live.ca056cd5-e2a6-4bd9-bef0-ab494f75c164
port = 2222
key_file = /Users/lindseycatlett/.ssh/id_rsa
shell_type = unix

[wp-cs-test-dev]
type = sftp
user = dev.33e9a797-133a-45ee-98b1-3027de8fa2fe
port = 2222
key_file = /Users/lindseycatlett/.ssh/id_rsa
shell_type = unix
md5sum_command = none
sha1sum_command = none
host = appserver.dev.33e9a797-133a-45ee-98b1-3027de8fa2fe.drush.in

