[tools]
bun = "latest"
go = "latest"
"go:github.com/steveyegge/beads/cmd/bd" = "latest"
node = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@mermaidchart/cli" = "latest"
php = "8.3"
python = ["3.12", "3.13", "3.11", "3.14"]
uv = "latest"
bat = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
delta = "latest"
hyperfine = "latest"
dust = "latest"
duf = "latest"
glow = "latest"
starship = "latest"
zoxide = "latest"
direnv = "latest"
act = "latest"
gh = "latest"
git-cliff = "latest"
shellcheck = "latest"
hadolint = "latest"
tmux = "latest"
gum = "latest"
cmake = "latest"
yq = "latest"
"github:BurntSushi/ripgrep" = "latest"
gemini-cli = "latest"
